baseURL = "/"
languageCode = "dk"
title = "Lyskurven"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  showReadingTime = true
  showToc = false
  ShowCodeCopyButtons = true
  math = true
  disableThemeToggle = true
  defaultTheme = "light"

[params.profileMode]
  enabled = true
  title = "Lyskurven"
  subtitle = "Se de positive tendenser i verden"
  imageUrl = "images/logo.png"
  imageWidth = 160
  imageHeight = 160

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/lyskurven/lyskurven"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/company/lyskurven"

[[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/lyskurven.dk"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    identifier = "Hjem"
    name = "Hjem"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "kurver"
    name = "Kurver"
    url = "/kurver/"
    weight = 2

  [[menu.main]]
    identifier = "om"
    name = "Om"
    url = "/om/"
    weight = 3

[caches]
  [caches.images]
    dir = ':cacheDir/images'
